### PR TITLE
Store drafts directly in the res.locals map

### PR DESCRIPTION
**Pull request by DamianDunajski**
This PR stores drafts directly in `res.locals` scope. Storing drafts in user scope has the following drawbacks:

1. drafts and other elements of the local application state are not really something that describes a user and as such should not be there - it only makes user class grow as application grows
2. current middleware implementation forces any application consuming `cmc-draft-store-middleware` module to to store drafts within user object which enforces questioned data structure onto other project teams 
3. it raises unnecessary question whether to assign user object to variable and access its draft properties to or maybe reaching for drafts directly

### CODE REVIEW

**Comment by rlewan** [comment]
@geek-soft would you mind providing a PR description which tells why this change is needed?

**Comment by DamianDunajski** [comment]
Added PR description @rlewan

**Comment by rlewan** [comment]
Looks alright, waiting for corresponding frontend pull requests.

**Comment by DamianDunajski** [comment]
@rlewan here is corresponding frontend PR: https://github.com/hmcts/cmc-citizen-frontend/pull/216

**Review by timja — APPROVED** [review]

**Pull request merged**
